cryptocurrency_payment/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path
from cryptocurrency_payment import views

app_name = 'cryptocurrency_payment'
urlpatterns = [

    re_path(
        "payment/(?P<pk>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})/$",
        views.CryptoPaymentDetailView.as_view(),
        name='crypto_payment_detail',
    ),

]

tutorial/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from rest_framework import routers
from quickstart import views
from rest_framework.authtoken import views as v
from cryptocurrency_payment import urls as cryptocurrency_payment_urls
from django.conf.urls.static import static
from tutorial.settings import STATIC_ROOT, STATIC_URL

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'profiles', views.ProfileViewSet)
router.register(r'plans', views.PlanViewSet)


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('links/users/create/', views.create_myuser),
    path('admin/', admin.site.urls),
    path('links/', include(router.urls)),
    path('', views.apiOverview),
    path('transactions/create', views.transactCreate),
    path('transactions', views.transactDetails),
    path('login/', views.login_user),
    path('logout/', views.user_logout),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-token-auth/', v.obtain_auth_token),
    re_path(r'^', include(cryptocurrency_payment_urls)),
] + static(STATIC_URL, document_root=STATIC_ROOT)

cryptocurrency_payment/models.py
# -*- coding: utf-8 -*-
from uuid import uuid4

from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from cryptocurrency_payment.app_settings import get_backend_config, get_backend_obj


def create_child_payment(payment, fiat_amount):
    """
    Create a child payment from a particular payment. A child payment can be created for a particular underpaid amount
    :param payment: The parent payment
    :param amount: The new fiat_amount. fiat_currency is the same as parent fiat_currency
    :return: payment oj
    """
    child_payment = create_new_payment(
        payment.crypto,
        fiat_amount=fiat_amount,
        fiat_currency=payment.fiat_currency,
        payment_title=payment.payment_title,
        payment_description=payment.payment_description,
        related_object=payment.content_object,
        user=payment.user,
        parent_payment=payment,
    )
    payment.child_payment = child_payment
    payment.save()
    return child_payment


def create_new_payment(
    crypto,
    fiat_amount,
    fiat_currency,
    payment_title=None,
    payment_description=None,
    related_object=None,
    user=None,
    parent_payment=None,
    address_index=None,
    reuse_address=None,
):
    """
    Create a cryptocurrency payment by using this method instead of creating directly on through the main model
    It helps with generation of addresses and fait conversion. Call these method directly to create a payment
    :param crypto: The crypto in config this transaction belongs too
    :param fiat_amount: The fiat amount of this transaction
    :param fiat_currency: The fiat currency of this transaction
    :param payment_title: Title you want on the payment
    :param payment_description: Description of the payment
    :param related_object: A generic object of another model that can be linked to this payments payment can be accessed from the model with object.payments.
    :param user: User that owns the payment for non anonymous payment
    :param parent_payment: The parent payment for subpayment or underpaid payments
    :param address_index: Use a particular generated address index for address generation see merchant-wallet
    :return: payment obj
    """
    crypto_reuse_address = reuse_address or get_backend_config(
        crypto, key="REUSE_ADDRESS"
    )
    crypto_code = get_backend_config(crypto, key="CODE")
    backend_obj = get_backend_obj(crypto)

    crypto_amount = backend_obj.convert_from_fiat(fiat_amount, fiat_currency)
    address = None
    resuse_address = False
    related_object_id = None
    if related_object:
        related_object_id = related_object.pk
    if parent_payment:
        address = parent_payment.address
        resuse_address = True
    if not address and crypto_reuse_address is True:
        address = CryptoCurrencyPayment.get_crypto_reused_address(crypto)
        resuse_address = address is not None
    if not address:
        address_generated_count = (
            address_index or CryptoCurrencyPayment.get_address_used_count(crypto)
        )
        address = backend_obj.generate_new_address(index=address_generated_count)
    payment = CryptoCurrencyPayment(
        crypto=crypto,
        crypto_code=crypto_code,
        address=address,
        crypto_amount=crypto_amount,
        fiat_amount=fiat_amount,
        fiat_currency=fiat_currency,
        payment_title=payment_title,
        payment_description=payment_description,
        address_reused=resuse_address,
        user=user,
        object_id=related_object_id,
        content_object=related_object,
        parent_payment=parent_payment,
    )
    if fiat_amount == 0:
        payment.status = CryptoCurrencyPayment.PAYMENT_PAID
    payment.save()
    return payment


class CryptoCurrencyPayment(models.Model):
    """
    Cryptocurrencypayment model to handle all cryptocurrency transactions and transaction status
    underpaid balance payment are recorded as child payment with their parent linked
    """

    PAYMENT_PAID = "paid"
    PAYMENT_CANCELLED = "cancelled"
    PAYMENT_NEW = "new"
    PAYMENT_PROCESSING = "processing"

    TRANSACTION_STATUS = (
        (PAYMENT_NEW, "New"),
        (PAYMENT_PAID, "Paid"),
        (PAYMENT_CANCELLED, "Cancelled"),
        (PAYMENT_PROCESSING, "Processing"),
    )
    id = models.UUIDField(
        default=uuid4, editable=False, primary_key=True, verbose_name="ID",
    )
    crypto = models.CharField(max_length=50)
    crypto_code = models.CharField(max_length=15, null=True)
    address = models.CharField(max_length=200)
    address_reused = models.BooleanField(default=False)
    tx_hash = models.CharField(max_length=150, null=True, help_text="Transaction ID")

    status = models.CharField(
        choices=TRANSACTION_STATUS, default=PAYMENT_NEW, max_length=50
    )

    crypto_amount = models.DecimalField(
        max_digits=17, decimal_places=12, help_text="Calculated crypto amount for fiat"
    )
    paid_crypto_amount = models.DecimalField(
        max_digits=17,
        decimal_places=12,
        help_text="Paid crypto amount",
        null=True,
        default=0,
    )
    fiat_amount = models.DecimalField(
        max_digits=9, decimal_places=2, help_text="Fiat amount"
    )
    fiat_currency = models.CharField(max_length=5, default="USD")
    payment_title = models.CharField(max_length=100, null=True)
    payment_description = models.CharField(max_length=250, null=True)
    user = models.ForeignKey(
        get_user_model(),
        null=True,
        on_delete=models.CASCADE,
        related_name="crypto_payments",
    )
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True)
    object_id = models.CharField(null=True, max_length=100)
    content_object = GenericForeignKey("content_type", "object_id")
    parent_payment = models.OneToOneField(
        "self", null=True, on_delete=models.CASCADE, related_name="child"
    )
    child_payment = models.OneToOneField(
        "self", null=True, on_delete=models.SET_NULL, related_name="parent"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {} {} {}".format(
            self.crypto_amount, self.address, self.fiat_amount, self.fiat_currency
        )

    @classmethod
    def get_crypto_reused_address(cls, crypto):
        """
        Get an address from old paid transaction when reusing address
        :param crypto: The crypto to get its address
        :return:
        """

        previous_payment = (
            cls.objects.filter(crypto=crypto, status=cls.PAYMENT_PAID)
            .order_by("updated_at")
            .first()
        )
        if previous_payment:
            address = previous_payment.address
            return address

    @classmethod
    def get_address_used_count(cls, crypto):
        """
        Get the total number of addresses generated for a particluar crypto currency
        :param crypto:
        :return:
        """
        return cls.objects.filter(crypto=crypto).count()

    @property
    def remaining_crypto_amount(self):
        if self.crypto_amount > self.paid_crypto_amount:
            return self.crypto_amount - self.paid_crypto_amount

    @property
    def is_under_paid(self):
        if self.paid_crypto_amount and self.remaining_crypto_amount:
            return True
        return False

cryptocurrency_payment/test_utils/test_app/models.py
from django.db import models

# Put your test models here
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation

from cryptocurrency_payment.models import CryptoCurrencyPayment


class Invoice(models.Model):

    payments = GenericRelation(CryptoCurrencyPayment)
    title = models.CharField(max_length=50)

cryptocurrency_payment/views.py
# -*- coding: utf-8 -*-
from django.views.generic import DetailView
from django.http import Http404
from cryptocurrency_payment.models import CryptoCurrencyPayment
from cryptocurrency_payment.app_settings import get_backend_config


class CryptoPaymentDetailView(DetailView):
    queryset = CryptoCurrencyPayment.objects.all()
    context_object_name = 'payment'
    template_name = 'cryptocurrency_payment/payment_detail.html'

    def get_object(self, *args ):

        obj = super(CryptoPaymentDetailView, self).get_object( *args )
        allow_anon_payment = get_backend_config(obj.crypto, key='ALLOW_ANONYMOUS_PAYMENT')
        # if  allow_anon_payment is not True and   self.request.user.is_authenticated is not True:
        #     raise Http404
        # elif   obj.user and self.request.user != obj.user:
        #     raise Http404
        return obj

cryptocurrency_payment/templates/cryptocurrency_payment/base.html
{% comment %}
As the developer of this package, don't place anything here if you can help it
since this allows developers to have interoperability between your template
structure and their own.

Example: Developer melding the 2SoD pattern to fit inside with another pattern::

    {% extends "base.html" %}
    {% load static %}

    <!-- Their site uses old school block layout -->
    {% block extra_js %}

        <!-- Your package using 2SoD block layout -->
        {% block javascript %}
            <script src="{% static 'js/ninja.js' %}" type="text/javascript"></script>
        {% endblock javascript %}

    {% endblock extra_js %}
{% endcomment %}

cryptocurrency_payment/templates/cryptocurrency_payment/payment_detail.html
<style>
.abf-frame p {
	font-family: Helvetica!important;
	line-height: 18px;
	margin: 0!important;
	padding: 0!important
}
.abf-frame {
	color: #000!important;
	background-color: #fff!important;
	position: absolute;
	top: calc(50% - 245px);
	left: calc(50% - 180px);
	font-family: Helvetica!important;
	width: 360px;
	max-height: 600px;
	margin-top: 0;
	text-align: left;
	box-shadow: 0 12px 28px rgba(0,0,0,0.1);
	border-radius: 3px;
	font-size: 12px
}
.abf-frame a {
	font-family: Helvetica!important;
	color: #6A8FC2!important
}
.abf-frame a:hover {
	color: #676573!important
}
.abf-form {
	padding: 0 24px 24px
}
.abf-header {
	display: flex;
	flex-direction: row;
	justify-content: space-between;
	align-items: center;
	padding: 5px 24px;
	min-height: 93px
}
.abf-header div:nth-child(1) img {
	display: inline-block;
	margin: 5px 0
}
.abf-ash1 {
	text-align: center;
	font-size: 14px;
	margin: 12px 0
}
.abf-ash2 {
	font-size: 14px;
	text-align: center;
	margin: 12px 0;
	font-weight: 700
}
.abf-topline {
	border-top: 1px solid #dedede!important;
	padding-top: 12px
}
.abf-list-item {
	padding: 4px 0;
	display: flex;
	align-items: baseline
}
.abf-label {
	display: inline-block;
	width: 45%;
	padding-right: 24px;
	box-sizing: border-box;
	vertical-align: top;
	font-size: 12px;
	opacity: .5;
	text-align: right
}
.abf-value {
	display: inline-block;
	width: 48%;
	box-sizing: border-box
}
.abf-confirmations {
	display: inline-block;
	background-color: #dc3545!important;
	width: 12px;
	height: 12px;
	font-size: 9px;
	line-height: 12px;
	text-align: center;
	color: #fff!important;
	border-radius: 50%;
	margin-left: 3px
}
.abf-green {
	background-color: #28a745!important
}
.abf-img-height {
	max-height: 80px
}

</style>
<div class="abf-frame">
  <div class="abf-header">
    <div>
      <div class="abf-ash1"><img src="https://bitcoinsymbol.org/i/old-bitcoin-logo.svg" width="50" alt=""></div>
    </div>
    <div style="text-align: center; background-color:#fff;"><span class="abf-qr"> <img class="abf-img-height" src="https://chart.googleapis.com/chart?chs=100x100&cht=qr&chl=bitcoin:{{payment.address}}?amount={{payment.crypto_amount}}&label={{payment.payment_title}}&message={{payment.payment_description}}" style="display: inline;" alt="QR code for payment"> </span> </div>
  </div>
  <div class="abf-form">
    <div class="abf-ash1"> Please send <strong><span class="abf-totalbtc">{{payment.crypto_amount}}</span></strong> {{payment.crypto_code}}
      to address: </div>
    <div class="abf-address abf-topline abf-ash2 abf-input-address"><a href="bitcoin:{{payment.address}}?amount={{payment.crypto_amount}}&label={{payment.payment_title}}&message={{payment.payment_description}}"> {{payment.address}}</a></div>
    <div class="abf-data abf-topline">
      <div class="abf-list">
         {% if payment.payment_title %}
              <div class="abf-list-item">
          <div class="abf-label">Title</div>
          <div class="abf-value">{{payment.payment_title}}</div>
        </div>
        {% endif %}
         {% if payment.payment_description %}
          <div class="abf-list-item">
          <div class="abf-label">Description</div>
          <div class="abf-value">{{payment.payment_description}}</div>
        </div>
        {% endif %}


        <div class="abf-list-item">
          <div class="abf-label">Amount to pay:</div>
          <div class="abf-value"><span class="abf-totalbtc">{{payment.crypto_amount}}</span> {{payment.crypto_code}}</div>
        </div>
        <div class="abf-list-item">
          <div class="abf-label">Arrived amount:</div>
          <div class="abf-value"><span class="abf-arrived">{{payment.paid_crypto_amount}}</span> {{payment.crypto_code}}</div>
        </div>
        <div class="abf-list-item">
          <div class="abf-label">Remains to pay:</div>
          <div class="abf-value"><b><span class="abf-remains">{{payment.remaining_crypto_amount}}</span> {{payment.crypto_code}}</b>
           <br />
          {% if payment.child_payment %}
               <div><a href="{% url 'cryptocurrency_payment:crypto_payment_detail' pk=payment.child_payment.pk %}" target="_blank">Click Here To Pay</a></div>
          {% endif %}
          </div>

        </div>
        <div class="abf-list-item">
          <div class="abf-label">Date:</div>
          <div class="abf-value">{{payment.created_at}}</div>
        </div>
            {% if payment.tx_hash %}
                 <div class="abf-list-item abf-tx-block">
          <div class="abf-label">Transaction(s):</div>
          <div class="abf-value abf-tx">
            <div><a href="https://live.blockcypher.com/btc/tx/{{payment.tx_hash}}/" target="_blank">{{payment.tx_hash | truncatechars:25}}</a>

            </div>
          </div>
        </div>
        {% endif %}

        <div class="abf-list-item">
          <div class="abf-label">Status:</div>
          <div class="abf-value"><b><span class="abf-status">{{payment.status | title}}</span>
          {% if payment.status != 'paid' or  payment.status != 'cancelled'  %}
            <br /><small style="color:blue">Confirmation may take 10m-20m</small>
            {% endif %}
          </b>
           <br />
           {% if payment.parent_payment %}
        <div>  <a href="{% url 'cryptocurrency_payment:crypto_payment_detail' pk=payment.parent_payment.pk %}"> Initial Payment </a></div>
            {% endif %}
          </div>

        </div>
      </div>
    </div>
  </div>
</div>